### ISSUE TITLE
Problems with dependencies still being included in class path 

### ISSUE THREAD

**Issue by Agrigohar** [Minecrell/plugin-yml#48]
Hi, I am unsure if this is an issue with the project or if I am just using it wrong. But I've tried it for 5 sessions now without success and I am a bit frustrated so I thought I would just ask.

I have 2 main questions:

1. I am using the libs.versions.toml for the dependency versions. I am using [kSpigot](https://github.com/jakobkmar/KSpigot) to have better Kotlin support while developing my plugin. I have added it to my dependencies via library(), even tough I have configured paper to generate the libraries.json the dependency does not get downloaded and the plugin does not load because it is missing it. Is that because kSpigot changes something about how plugins are loaded or am I doing something wrong?

  
2. I have added the kotlin stdlib as a library() dependency but my compiled jar still contains "kotlin" and "kotlinx" and other kotlin related stuff. What am I doing wrong there?

Thx for your help!

Snippet from build.gradle.kts:
```kotlin
dependencies {
    library(kotlin("stdlib"))
    library(libs.adventureApi)
    library(libs.adventureMiniMessage)

    library(libs.kSpigot)

    paperweight.paperDevBundle("1.20.1-R0.1-SNAPSHOT")
}

paper {
    website = "Website.de"
    version = pluginVersion
    description = "..."
    authors = listOf("Author1", "Author2")

    main = "<My main class>"

    foliaSupported = false
    apiVersion = "1.20"
    generateLibrariesJson = true
}
```

<details>
  <summary>Entire build.gradle.kts</summary>
  
  ```kotlin
val repoUsername: String by project
val repoPassword: String by project
val langTestServerLocation: String by project

plugins {
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.paperweight)
    alias(libs.plugins.pluginYmlPaper)
    alias(libs.plugins.shadow)
    `maven-publish`
}

val serverTestVersion = setOf("1.20")

val pluginVersion = "1.1.0"

repositories {
    mavenCentral()
    maven {
        url = uri("<my-repo>")
        credentials {
            username = repoUsername
            password = repoPassword
        }
    }
    maven("https://repo.cloudnetservice.eu/repository/releases/")
}

dependencies {
    library(kotlin("stdlib"))
    library(libs.adventureApi)
    library(libs.adventureMiniMessage)

    library(libs.kSpigot)

    paperweight.paperDevBundle("1.20.1-R0.1-SNAPSHOT")
}

paper {
    website = "Website.de"
    version = pluginVersion
    description = "..."
    authors = listOf("Author1", "Author2")

    main = "<My main class>"

    foliaSupported = false
    apiVersion = "1.20"
    generateLibrariesJson = true
}

publishing {
    repositories {
        maven {
            name = "repoPrivate"
            url = uri("<my-repo>>")
            credentials {
                username = repoUsername
                password = repoPassword
            }
        }
    }
    publications {
        create<MavenPublication>("maven") {
            groupId = "<class>"
            artifactId = "<name>"
            version = pluginVersion
            from(components["java"])
        }
    }
}

tasks.jar {
    val dependencies = configurations
        .runtimeClasspath
        .get()
        .map(::zipTree)
    from(dependencies)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}



tasks {
    build {
        dependsOn(reobfJar)
    }
    compileJava {
        options.encoding = "UTF-8"
        options.release.set(17)
    }
    compileKotlin {
        kotlinOptions.jvmTarget = "17"
    }
}

tasks.register("deploy") {
    group = "deploy"
    description = "Deploys the plugin to the server"
    dependsOn(tasks.shadowJar)
    doLast {
        for (serverTestVersion in serverTestVersion) {
            val serverDirectory = File(langTestServerLocation, serverTestVersion)
            val pluginDirectory = File(serverDirectory, "plugins")
            val pluginFile = File(pluginDirectory, "${project.name}.jar")
            if (pluginFile.exists()) {
                pluginFile.delete()
            }
            pluginFile.createNewFile()
            pluginFile.writeBytes(tasks.shadowJar.get().archiveFile.get().asFile.readBytes())
        }
    }
}

  ```
  
</details>

**Comment by stephan-gh** [comment]
1. You need to set the `loader` class in the `paper { ... }` block.
2. I'm not sure. This part is a bit suspicious and looks like it would include classes from dependencies in your plugin JAR. Why do you need it? Same for the shadow plugin.

    ```kotlin
    tasks.jar {
      val dependencies = configurations
          .runtimeClasspath
          .get()
          .map(::zipTree)
      from(dependencies)
      duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    ```

    If you want to use the library mechanism you shouldn't need any of this.

    It doesn't fully explain the problem though. kotlin-stdlib shouldn't actually end up in the `runtimeClasspath`, since `library` should be a `compileOnly` dependency. Maybe check `./gradlew :dependencies` to get a list of dependencies and see if kotlin is actually on the runtimeClasspath and why.

**Comment by Agrigohar** [comment]
Thx for your quick response, the second issue has been solved. It seems like I copied the code snippet in at sometime and then just categorically overlooked it. Removing it solved the issue.  

I've referenced my main class as loader in paper, the same class that is also named under `paper.main`. But at plugin startup the server doesn't find the kspigot class:
`[EntrypointUtil] net/axay/kspigot/main/KSpigot
java.lang.NoClassDefFoundError: net/axay/kspigot/main/KSpigot`

And it is also not downloaded in the libraries folder in the server directory. But it referenced in the paper-libraries.json in the jar.

**Comment by stephan-gh** [comment]
You need to create a custom `PluginLoader` class, see https://github.com/Minecrell/plugin-yml#paper-1 ("Example PluginLoader").

In many cases it might be easier to declare a `bukkit { ... }` plugin instead. In that case you don't need a `PluginLoader` because Bukkit/Spigot plugins can declare libraries in `plugin.yml`. You can still use most of the Paper-specific API from a good old Bukkit/Spigot plugin.

Personally I would suggest using a Paper plugin only if you are sure that you can benefit from the new/extra functionality offered by those.

**Comment by Agrigohar** [comment]
Okay, yes replacing pluginYml for Paper with the bukkit version solved the issue for me. Thx a whole lot!
But how can I add my own libraries that are not on maven central? I've tried to shade them into the plugin using shadow. But everytime I use shadow the kotlin libraries and a whole lot more get included again.

**Comment by stephan-gh** [comment]
> But how can I add my own libraries that are not on maven central?

In this case you could either use a custom PluginLoader for a Paper plugin, which would let you configure additional Maven repositories (see `resolver::addRepository`) in the example I linked.

> I've tried to shade them into the plugin using shadow. But everytime I use shadow the kotlin libraries get included again.

Well, it's still not clear to me why you have kotlin on the `runtimeClasspath` used by shadow (see my first comment). It would be good to figure out why that happens, but you could also explicitly include only the dependencies you want (see https://imperceptiblethoughts.com/shadow/configuration/dependencies/#filtering-dependencies).

**Comment by Agrigohar** [comment]
Thanks a lot for your help! I was able to shade the required dependency into the plugin using:
```kotlin
tasks.shadowJar {
        dependencies {
            include(<My Dependency>)
        }
}
```
